### ISSUE TITLE
Why train on spectrogram but decompose into mag and phase for inference

### ISSUE THREAD

**Issue by lminer** [Xiao-Ming/UNet-VocalSeparation-Chainer#4]
This implementation is great. Was just wondering why you train on the spectrogram, but when inference time comes around, you decompose the spectrogram into magnitude and phase and then apply the mask to the magnitude. Shouldn't we be training on the magnitude as well?

**Comment by Xiao-Ming** [comment]
The training does work on magnitude spectrogram, the same as inference.

**Comment by lminer** [comment]
I see. You're absolutely right. You calculate phase in the inference stage but not in the training stage and that tripped me up. My bad!
