### ISSUE TITLE
10 minutes song

### ISSUE THREAD

**Issue by farwiayas** [Xiao-Ming/UNet-VocalSeparation-Chainer#7]
Hi,
Can you please give me the settings to separate 10 minues song because  DoExperiment.py give only 30 sec.
Thanks
Regards

**Comment by Xiao-Ming** [comment]
You can do it by modifying the `start` and `end` variables in the example code. Set `start = 0` and `end` any number multiple of 512.
For example, set `end=mag.shape[1] // 512 * 512`. If you want the whole song be processed you can consider padding zeros to the spectrogram matrix.

**Comment by farwiayas** [comment]
[Xiao-Ming] you are genius.
Thank you very much.
Best regards
